# Generated by Django 4.2.29 on 2026-04-23 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posthog", "1120_backfill_provisioning_skip_existing_user_consent"),
    ]

    operations = [
        migrations.CreateModel(
            name="IntegrationRepositoryCacheEntry",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.TextField()),
                ("description", models.TextField(blank=True, null=True)),
                ("topics", models.JSONField(blank=True, default=list)),
                ("archived", models.BooleanField(default=False)),
                ("fork", models.BooleanField(default=False)),
                ("primary_language", models.TextField(blank=True, null=True)),
                ("default_branch", models.TextField()),
                ("default_branch_sha", models.TextField()),
                ("readme", models.TextField(blank=True, default="")),
                ("tree_paths", models.TextField(blank=True, default="")),
                ("tree_truncated", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "integration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="repository_cache_entries",
                        to="posthog.integration",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="posthog.team"),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["team", "updated_at"],
                        name="posthog_int_team_id_dc6d07_idx",
                    ),
                    models.Index(
                        fields=["integration", "full_name"],
                        name="posthog_int_integra_7fa8c3_idx",
                    ),
                ],
                "unique_together": {("integration", "full_name")},
            },
        ),
    ]
